# Ameba configuration for work_trees library
Version: "1.7.0-dev"

Excluded:
  - temp/**/*
  - lib/**/*
  - vendor/**/*
  - spec/**/*

# add paths that need to be excluded so we track in one place
# Metrics/CyclomaticComplexity:
#   Excluded:
#     -
